### ISSUE TITLE
AdoptOpenJDK vendor not used/detected after install

### ISSUE THREAD

**Issue by StevenJDH** [AdoptOpenJDK/install-jdk#21]
I recently started using the `maven-enforcer-plugin` to warn if AdoptOpenJDK as a Java vendor wasn't being used, which works locally, but after the first pipeline run, it detected a different vendor in use as you can see here:

```bash
1247  Warning:  Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVendor warned with message:
1248  Eclipse Foundation is not an included Required Java Vendor
```

The expectation is that this would not throw a warning because I use `AdoptOpenJDK/install-jdk@v1.1.1` before this step with the following configuration:

```yaml
- name: Install AdoptOpenJDK
  uses: AdoptOpenJDK/install-jdk@v1.1.1
  with:
    version: '16'
    architecture: x64
    impl: hotspot
```

Is something in the environment not being set by this action that causes ` Eclipse Foundation` to be the detected vendor that my project is compiling against? 

I will be testing soon to see if using `actions/setup-java` produces the same result as this action is now more configurable with import features like configuring the global settings.xml file for automated deployments to maven central, however, for regular build workflows, I still prefer to use `AdoptOpenJDK/install-jdk`.
